### ISSUE TITLE
handleDelete 

### ISSUE THREAD

**Issue by vertjs** [vertjs/ra16-homeworks#1]
какая-то ошибка в методе handleDelete компонента Crud (не удаляется заметка)

  const handleDelete = id => {
    fetch(`${process.env.REACT_APP_API_URL}/:${id}`, {
      method: 'DELETE',
      headers: {
        'Content-Type': 'application/json;charset=utf-8'
      },
      body: JSON.stringify(notes[id])
    })
    .then(response => console.log(response)) // {return response.json()}
    .then(result => console.log(result)) //setNotes(prevNotes => prevNotes.filter( o => o.id !== id))
    
  }

**Comment by coursar** [comment]
Двоеточия быть не должно:
https://github.com/vertjs/ra16-homeworks/blob/535d731d51a8d5fbb5be9953baec28b3ec18fa52/lifecycle-http/crud/frontend/src/Crud.js#L33-L34
