### ISSUE TITLE
Unhandled Rejection (Invariant Violation) при передаче данных в setData

### ISSUE THREAD

**Issue by vertjs** [vertjs/ra16-homeworks#2]
При передаче данных с сервера в setData ошибка (компонент useJsonFetch)
×
Unhandled Rejection (Invariant Violation): Objects are not valid as a React child (found: object with keys {id, content, created}). If you meant to render a collection of children, use an array instead.
   in span (at HeadPage.js:10)
   in div (at HeadPage.js:8)
   in HeadPage (at App.js:11)
   in Route (at App.js:10)
   in Router (created by BrowserRouter)
   in BrowserRouter (at App.js:9)
   in App (at src/index.js:7)

**Comment by coursar** [comment]
Ошибка не в этом. Вы должны посмотреть, куда делается запрос и увидеть, что вы забыли создать файл .env или не прописали в него REACT_APP_DATA_URL=http://localhost:7070

**Comment by vertjs** [comment]
.env есть, просто попал в giignor

**Comment by coursar** [comment]
так выложите целиком ))
