### ISSUE TITLE
не получается заполнить поле добавления после нажатия на карандаш (редактирование)

### ISSUE THREAD

**Issue by vertjs** [vertjs/ra16-homeworks#6]
проблема в components/ServiceList.js, функция handleEdit - 
не понимаю как заполнить форму добавления при нажатии на кнопку редактировать  
https://github.com/vertjs/ra16-homeworks/blob/master/redux/editing/frontend/src/components/ServiceList.js

**Comment by coursar** [comment]
Один из вариантов. Вы можете разнести функциональность редактирования существующего и добавления нового.
