### ISSUE TITLE
Failed to execute 'fetch' on 'Window': 'DELETE ' is not a valid HTTP method.

### ISSUE THREAD

**Issue by vertjs** [vertjs/ra16-homeworks#7]
почему при удалении возникает ошибка ?

>  'DELETE ' is not a valid HTTP method.

export const removeServicesUpload = (id) => async (dispatch) => {
  console.log(`${process.env.REACT_APP_API_URL+'/'+id}`)
  dispatch(removeService(id));
  try {
    const response = await fetch(`${process.env.REACT_APP_API_URL+'/'+id}`, {
      method: 'DELETE ',
      headers: {'Content-Type': 'application/json'}
    });
    if (!response.ok) {
      throw new Error(response.statusText);
    }
    const data = await response.json();
    dispatch(removeService(id));
  } catch (error) {
    console.log(error.message);
  }
}

https://github.com/vertjs/ra16-homeworks/tree/master/redux/api/frontend/src/actions

**Comment by coursar** [comment]
`headers` уберите

**Comment by vertjs** [comment]
не помогло

**Comment by coursar** [comment]
А сообщение на фронте или на бэке?

**Comment by vertjs** [comment]
вроде на фронте

**Comment by coursar** [comment]
вы опять .env не залили

**Comment by coursar** [comment]
`method: 'DELETE '` - метод называется 'DELETE' без пробела, а у вас пробел в строке.

```js
export const removeServicesUpload = (id) => async (dispatch) => {
  console.log(`${process.env.REACT_APP_API_URL+'/'+id}`)
  dispatch(removeService(id));
  try {
    const response = await fetch(`${process.env.REACT_APP_API_URL+'/'+id}`, {
      method: 'DELETE'
    });
    if (!response.ok) {
      throw new Error(response.statusText);
    }
    dispatch(removeService(id));
  } catch (error) {
    console.log(error.message);
  }
}
```

**Comment by vertjs** [comment]
Спасибо Большое ))
