### ISSUE TITLE
Нужна подсказка )

### ISSUE THREAD

**Issue by vertjs** [vertjs/ra16-homeworks#8]
не понимаю как отдиспатчить данные из form, чтоб при переходе со страницы редактирования на главную, данные записывались. Пытаюсь передать в функции handleSubmit (https://github.com/vertjs/ra16-homeworks/blob/master/redux/api/frontend/src/components/CurrentElement.js)

**Comment by vertjs** [comment]
разобралась

**Comment by coursar** [comment]
Низя писать смайлики в названии Issue. Всё должно быть серьёзно ))
